#!/usr/bin/env zsh
# shellcheck shell=bash
set -eEuo pipefail
IFS=$'\n\t '

main() {
    echo "$ZSH_VERSION"
}

# shellcheck disable=SC2154
if [[ "${zsh_eval_context[-1]}" == 'toplevel' ]]; then
    main
fi
