#!/usr/bin/env zsh
# shellcheck shell=bash
unset IFS
set -eEuo pipefail

main() {
    echo "$ZSH_VERSION"
}

# shellcheck disable=SC2154
if [[ "${zsh_eval_context[-1]}" == 'toplevel' ]]; then
    main
fi
