#!/usr/bin/env ash

if [ -f /usr/bin/dpkg ]; then
    dpkg -l ash
elif [ -f /usr/local/bin/brew ]; then
    brew list ash
elif [ -f /usr/bin/yum ]; then
    yum -l ash
elif [ -f /usr/bin/emerge ]; then
    emerge -Opv ash
elif [ -f /usr/bin/pacman ]; then
    pacman -Qi ash
fi
